### PR TITLE
Ai engine

### PR DESCRIPTION
**Pull request by zandihudson**
Backend functionality for chatbot that reads files in data folder and answers query

### CODE REVIEW

**Review by JereLew — COMMENTED** [review]
The ai-engine looks clean, functionality works well. Advising recommendations are presented clearly.

**Comment by NBuckle** [comment]
I think this is my favorite part of the project. Good job Azandria! I think this function will get used the most in production

**Comment by rianabattick** [comment]
Utilizing AI for advising is brilliant. Functionality works great! Nice work!

**Comment by ajaimesonshirley** [comment]
The ai-engine works well, and utilizes chatgpt very well. Well done!

**Pull request closed without merging**
