### PR TITLE
Frontend riana

### PR DESCRIPTION
**Pull request by rianabattick**
This branch created the frontend of the Bison Advisor app for the homepage, login, admin dashboard, self service page(s) and course catalog pages. The UI was built using Html and CSS utilizing unique styling, and appropriate features to accommodate the backend code.

### CODE REVIEW

**Comment by NBuckle** [comment]
I like that both you and Jeremiah both kept the files and templates consistent. All the buttons go to desired pages as well. Good job

**Review by JereLew — COMMENTED** [review]
Styling and functionality works well, I like how the code is easy to follow. Good work!

**Comment by zandihudson** [comment]
The style is very consistent with the color of the banners, font, and text size. This really helps the application feel complete great job

**Comment by ajaimesonshirley** [comment]
The layout is good and very easy to folllow, and everything works well. Nice job!

**Pull request closed without merging**
