### PR TITLE
Frontend jeremiah

### PR DESCRIPTION
**Pull request by JereLew**
This PR validates the code for the html files for student usage.

### CODE REVIEW

**Comment by NBuckle** [comment]
Everything is clear and concise. I like that you kept everything consistent. It makes readability and usability a lot easier

**Comment by rianabattick** [comment]
Code is very readable with many comments.

**Comment by zandihudson** [comment]
The code is really easy to follow and all entry boxes and buttons are organized. This really aided in being able to connect the backend functionality

**Comment by ajaimesonshirley** [comment]
The code is very easy to read and understand. It's well put together, well done.

**Pull request closed without merging**
