### PR TITLE
Advising and self service

### PR DESCRIPTION
**Pull request by NBuckle**
Fixed alll functions for Admin Dashboard and Self Service

### CODE REVIEW

**Review by JereLew — COMMENTED** [review]
Code is clean, passes various test cases. Data manipulation and retrieval works well.

**Comment by rianabattick** [comment]
Great work!

**Comment by zandihudson** [comment]
The functions are clean and run smoothly. I didn't have any trouble following the variable names and understanding the purpose of each function

**Comment by ajaimesonshirley** [comment]
Code is easy to read, and test cases are passed.  Nice work!

**Pull request closed without merging**
